#spring.application.name=order-service
#server.port=8082
#
## Added ?createDatabaseIfNotExist=true to automatically create the schema
#spring.datasource.url=jdbc:mysql://localhost:3307/orderdb?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=devashri
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA & Hibernate Settings
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
## Target URL for Inventory Service (running on port 8083)
#inventory.service.url=http://localhost:8083
server.port=8081
spring.application.name=order-service

# Connect to inventory-mysql on port 3307
spring.datasource.url=jdbc:mysql://localhost:3307/orderdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=devashri

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Inventory Service Endpoint
inventory.service.url=http://localhost:8083

# Swagger UI custom path
springdoc.swagger-ui.path=/swagger-ui.html

# OpenAPI JSON description endpoint
springdoc.api-docs.path=/api-docs

# Enable or disable OpenAPI spec generation
springdoc.api-docs.enabled=true