##spring.application.name=product.service
#spring.data.mongodb.uri=mongodb://admin:devashri@localhost:27017/product-service?authSource=admin
spring.mongodb.uri=mongodb://admin:devashri@localhost:27017/product-service?authSource=admin
# Swagger UI custom path
springdoc.swagger-ui.path=/swagger-ui.html

# OpenAPI JSON description endpoint
springdoc.api-docs.path=/api-docs

# Enable or disable OpenAPI spec generation
springdoc.api-docs.enabled=true