##spring.application.name=product.service
#spring.data.mongodb.uri=mongodb://admin:devashri@localhost:27017/product-service?authSource=admin
spring.mongodb.uri=mongodb://admin:devashri@localhost:27017/product-service?authSource=admin
